listening-port=3478
listening-ip=0.0.0.0

relay-ip=0.0.0.0
external-ip=192.168.0.10

realm=192.168.0.10
server-name=192.168.0.10

fingerprint
lt-cred-mech
user=test:test123

min-port=49160
max-port=49200

verbose
no-multicast-peers
log-file=stdout